version: '3.7'
services:
  backend:
    build:
      context: server-nodejs
      dockerfile: Dockerfile.dev
    entrypoint:
      - sleep
      - infinity
    depends_on:
      - primary
  primary:
    image: postgres
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=testdb
    volumes:
      - pg-vol-debug2:/var/lib/postgresql/data
volumes:
  pg-vol-debug2:
