services:
  backend:
    build:
      context: ./server-nodejs
      dockerfile: Dockerfile.debug
    ports:
      - '5000:5000'
    volumes:
      - ./server-nodejs:/app
    environment:
      - NODE_ENV=development
      - DB_HOST_PRIMARY=primary
      - DB_HOST_REPLICA=primary
  primary:
    hostname: 'primary'
    image: crunchydata/crunchy-postgres:centos8-13.6-4.7.5
    environment:
      - PGHOST=/tmp
      - MAX_CONNECTIONS=10
      - MAX_WAL_SENDERS=5
      - PG_MODE=primary
      - MODE=postgres
      - PG_PRIMARY_USER=primaryuser
      - PG_PRIMARY_PASSWORD=password
      - PG_DATABASE=testdb
      - PG_USER=testuser
      - PG_PASSWORD=password
      - PG_ROOT_PASSWORD=password
      - PG_PRIMARY_PORT=5432
    volumes:
      - pg-vol-debug:/pgdata
    deploy:
      placement:
        constraints:
          - node.labels.type == primary
          - node.role == worker
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - '5050:80'
  redis:
    image: bitnami/redis:latest
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

volumes:
  pg-vol-debug:
    driver: local
