networks:
  grpc-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.10.10.0/24

services:
  grpc-server-go:
    build: ./grpc-server-go
    image: skyface753/grpc-server-go
    ports:
      - 50051:50051
    depends_on:
      - primary
      - redis
      - minio
    environment:
      - POSTGRES_HOST=primary
      - REDIS_HOST=redis
      - S3_ENDPOINT=http://test.skyface.de:9000
    extra_hosts:
      - "test.skyface.de:10.10.10.5" # for minio
    networks:
      grpc-net:
        ipv4_address: 10.10.10.2


  primary:
    image: postgres
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=testdb
    volumes:
      - grpc-pg-vol-debug:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      grpc-net:
        ipv4_address: 10.10.10.3

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - '5050:80'
    volumes:
      - grpc-pgadmin-data:/var/lib/pgadmin
    depends_on:
      - primary
  

  redis:
    image: redis
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      grpc-net:
        ipv4_address: 10.10.10.4
  

  minio:
    image: docker.io/bitnami/minio:2022
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=minio-root-user
      - MINIO_ROOT_PASSWORD=minio-root-password
    volumes:
      - grpc-minio_data:/data
    networks:
      grpc-net:
        ipv4_address: 10.10.10.5

   



  envoy:
    build:
      context: ./grpc-envoy-proxy
      dockerfile: Dockerfile.macos
    ports:
      - 8000:8000
    depends_on:
      - grpc-server-go
   


volumes:
  grpc-pg-vol-debug:
  grpc-pgadmin-data:
  grpc-minio_data:


