version: '3.3'

services:
  backend:
    build:
      context: ./server-nodejs
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    networks:
      - crunchynet
    environment:
      - DB_HOST_PRIMARY=primary
      - DB_HOST_REPLICA=replica
      - DB_PORT_PRIMARY=5432
      - DB_PORT_REPLICA=5432
      - DB_USER=postgresUser
      - DB_PASSWORD=postgresPassword
      - DB_DATABASE=postgresDatabase
      - JWT_SECRET=jwtSecret
      - BCRYPT_ROUNDS=11
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=redisPassword
    depends_on:
      - redis
      - primary
      - replica

  primary:
    image: crunchydata/crunchy-postgres:centos8-13.6-4.7.5
    environment:
      - PGHOST=/tmp
      - MAX_CONNECTIONS=10
      - MAX_WAL_SENDERS=5
      - PG_MODE=primary
      - MODE=postgres
      - PG_PRIMARY_USER=primaryuser
      - PG_PRIMARY_PASSWORD=password
      - PG_DATABASE=postgresDatabase
      - PG_USER=postgresUser
      - PG_PASSWORD=postgresPassword
      - PG_ROOT_PASSWORD=password
      - PG_PRIMARY_PORT=5432
    networks:
      - crunchynet
    deploy:
      placement:
        constraints:
          - node.labels.type == primary
          - node.role == worker
    volumes:
      - primary-vol:/pgdata
    ports:
      - '5432'
  replica:
    image: crunchydata/crunchy-postgres:centos8-13.6-4.7.5
    environment:
      - PGHOST=/tmp
      - MAX_CONNECTIONS=10
      - MAX_WAL_SENDERS=5
      - PG_MODE=replica
      - MODE=postgres
      - PG_PRIMARY_HOST=primary
      - PG_PRIMARY_PORT=5432
      - PG_PRIMARY_USER=primaryuser
      - PG_PRIMARY_PASSWORD=password
      - PG_DATABASE=postgresDatabase
      - PG_USER=postgresUser
      - PG_PASSWORD=postgresPassword
      - PG_ROOT_PASSWORD=password
    networks:
      - crunchynet
    ports:
      - '5432'
    deploy:
      placement:
        constraints:
          - node.labels.type != primary
          - node.role == worker
      replicas: 2
    volumes:
      - replica-vol:/pgdata

  redis:
    image: redis
    networks:
      - crunchynet
networks:
  crunchynet:

volumes:
  primary-vol:
  replica-vol:
