/**
 * @fileoverview gRPC-Web generated client stub for template
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.1
// 	protoc              v3.20.3
// source: grpc-proto/avatar.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js')
const proto = {};
proto.template = require('./avatar_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.template.AvatarServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.template.AvatarServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.template.UploadGetUrlRequest,
 *   !proto.template.UploadGetUrlResponse>}
 */
const methodDescriptor_AvatarService_GetUploadURL = new grpc.web.MethodDescriptor(
  '/template.AvatarService/GetUploadURL',
  grpc.web.MethodType.UNARY,
  proto.template.UploadGetUrlRequest,
  proto.template.UploadGetUrlResponse,
  /**
   * @param {!proto.template.UploadGetUrlRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.template.UploadGetUrlResponse.deserializeBinary
);


/**
 * @param {!proto.template.UploadGetUrlRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.template.UploadGetUrlResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.template.UploadGetUrlResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.template.AvatarServiceClient.prototype.getUploadURL =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/template.AvatarService/GetUploadURL',
      request,
      metadata || {},
      methodDescriptor_AvatarService_GetUploadURL,
      callback);
};


/**
 * @param {!proto.template.UploadGetUrlRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.template.UploadGetUrlResponse>}
 *     Promise that resolves to the response
 */
proto.template.AvatarServicePromiseClient.prototype.getUploadURL =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/template.AvatarService/GetUploadURL',
      request,
      metadata || {},
      methodDescriptor_AvatarService_GetUploadURL);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.template.UploadConfirmRequest,
 *   !proto.template.UploadConfirmResponse>}
 */
const methodDescriptor_AvatarService_ConfirmUpload = new grpc.web.MethodDescriptor(
  '/template.AvatarService/ConfirmUpload',
  grpc.web.MethodType.UNARY,
  proto.template.UploadConfirmRequest,
  proto.template.UploadConfirmResponse,
  /**
   * @param {!proto.template.UploadConfirmRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.template.UploadConfirmResponse.deserializeBinary
);


/**
 * @param {!proto.template.UploadConfirmRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.template.UploadConfirmResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.template.UploadConfirmResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.template.AvatarServiceClient.prototype.confirmUpload =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/template.AvatarService/ConfirmUpload',
      request,
      metadata || {},
      methodDescriptor_AvatarService_ConfirmUpload,
      callback);
};


/**
 * @param {!proto.template.UploadConfirmRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.template.UploadConfirmResponse>}
 *     Promise that resolves to the response
 */
proto.template.AvatarServicePromiseClient.prototype.confirmUpload =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/template.AvatarService/ConfirmUpload',
      request,
      metadata || {},
      methodDescriptor_AvatarService_ConfirmUpload);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.protobuf.Empty,
 *   !proto.google.protobuf.Empty>}
 */
const methodDescriptor_AvatarService_Delete = new grpc.web.MethodDescriptor(
  '/template.AvatarService/Delete',
  grpc.web.MethodType.UNARY,
  google_protobuf_empty_pb.Empty,
  google_protobuf_empty_pb.Empty,
  /**
   * @param {!proto.google.protobuf.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  google_protobuf_empty_pb.Empty.deserializeBinary
);


/**
 * @param {!proto.google.protobuf.Empty} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.protobuf.Empty)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.protobuf.Empty>|undefined}
 *     The XHR Node Readable Stream
 */
proto.template.AvatarServiceClient.prototype.delete =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/template.AvatarService/Delete',
      request,
      metadata || {},
      methodDescriptor_AvatarService_Delete,
      callback);
};


/**
 * @param {!proto.google.protobuf.Empty} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.protobuf.Empty>}
 *     Promise that resolves to the response
 */
proto.template.AvatarServicePromiseClient.prototype.delete =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/template.AvatarService/Delete',
      request,
      metadata || {},
      methodDescriptor_AvatarService_Delete);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.template.GetAvatarViewRequest,
 *   !proto.template.GetAvatarViewResponse>}
 */
const methodDescriptor_AvatarService_GetAvatarView = new grpc.web.MethodDescriptor(
  '/template.AvatarService/GetAvatarView',
  grpc.web.MethodType.UNARY,
  proto.template.GetAvatarViewRequest,
  proto.template.GetAvatarViewResponse,
  /**
   * @param {!proto.template.GetAvatarViewRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.template.GetAvatarViewResponse.deserializeBinary
);


/**
 * @param {!proto.template.GetAvatarViewRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.template.GetAvatarViewResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.template.GetAvatarViewResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.template.AvatarServiceClient.prototype.getAvatarView =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/template.AvatarService/GetAvatarView',
      request,
      metadata || {},
      methodDescriptor_AvatarService_GetAvatarView,
      callback);
};


/**
 * @param {!proto.template.GetAvatarViewRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.template.GetAvatarViewResponse>}
 *     Promise that resolves to the response
 */
proto.template.AvatarServicePromiseClient.prototype.getAvatarView =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/template.AvatarService/GetAvatarView',
      request,
      metadata || {},
      methodDescriptor_AvatarService_GetAvatarView);
};


module.exports = proto.template;

