// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: grpc-proto/avatar.proto

package template

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Avatar struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GeneratedPath string `protobuf:"bytes,1,opt,name=generatedPath,proto3" json:"generatedPath,omitempty"`
	OriginalName  string `protobuf:"bytes,2,opt,name=originalName,proto3" json:"originalName,omitempty"`
	Type          string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *Avatar) Reset() {
	*x = Avatar{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_avatar_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Avatar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Avatar) ProtoMessage() {}

func (x *Avatar) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_avatar_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Avatar.ProtoReflect.Descriptor instead.
func (*Avatar) Descriptor() ([]byte, []int) {
	return file_grpc_proto_avatar_proto_rawDescGZIP(), []int{0}
}

func (x *Avatar) GetGeneratedPath() string {
	if x != nil {
		return x.GeneratedPath
	}
	return ""
}

func (x *Avatar) GetOriginalName() string {
	if x != nil {
		return x.OriginalName
	}
	return ""
}

func (x *Avatar) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type UploadGetUrlRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filename string `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
}

func (x *UploadGetUrlRequest) Reset() {
	*x = UploadGetUrlRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_avatar_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadGetUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadGetUrlRequest) ProtoMessage() {}

func (x *UploadGetUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_avatar_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadGetUrlRequest.ProtoReflect.Descriptor instead.
func (*UploadGetUrlRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_avatar_proto_rawDescGZIP(), []int{1}
}

func (x *UploadGetUrlRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type UploadGetUrlResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url            string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`                       // url to upload to s3
	TokenToConfirm string `protobuf:"bytes,2,opt,name=tokenToConfirm,proto3" json:"tokenToConfirm,omitempty"` // token to confirm upload (filename, originalname, type) -> save to db
}

func (x *UploadGetUrlResponse) Reset() {
	*x = UploadGetUrlResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_avatar_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadGetUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadGetUrlResponse) ProtoMessage() {}

func (x *UploadGetUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_avatar_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadGetUrlResponse.ProtoReflect.Descriptor instead.
func (*UploadGetUrlResponse) Descriptor() ([]byte, []int) {
	return file_grpc_proto_avatar_proto_rawDescGZIP(), []int{2}
}

func (x *UploadGetUrlResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *UploadGetUrlResponse) GetTokenToConfirm() string {
	if x != nil {
		return x.TokenToConfirm
	}
	return ""
}

type UploadConfirmRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"` // token to confirm upload (filename, originalname, type) -> save to db
}

func (x *UploadConfirmRequest) Reset() {
	*x = UploadConfirmRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_avatar_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadConfirmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadConfirmRequest) ProtoMessage() {}

func (x *UploadConfirmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_avatar_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadConfirmRequest.ProtoReflect.Descriptor instead.
func (*UploadConfirmRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_avatar_proto_rawDescGZIP(), []int{3}
}

func (x *UploadConfirmRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type UploadConfirmResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"` // url to get avatar from s3
}

func (x *UploadConfirmResponse) Reset() {
	*x = UploadConfirmResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_avatar_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadConfirmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadConfirmResponse) ProtoMessage() {}

func (x *UploadConfirmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_avatar_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadConfirmResponse.ProtoReflect.Descriptor instead.
func (*UploadConfirmResponse) Descriptor() ([]byte, []int) {
	return file_grpc_proto_avatar_proto_rawDescGZIP(), []int{4}
}

func (x *UploadConfirmResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type GetAvatarViewRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int32 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *GetAvatarViewRequest) Reset() {
	*x = GetAvatarViewRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_avatar_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAvatarViewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvatarViewRequest) ProtoMessage() {}

func (x *GetAvatarViewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_avatar_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvatarViewRequest.ProtoReflect.Descriptor instead.
func (*GetAvatarViewRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_avatar_proto_rawDescGZIP(), []int{5}
}

func (x *GetAvatarViewRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetAvatarViewResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *GetAvatarViewResponse) Reset() {
	*x = GetAvatarViewResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_avatar_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAvatarViewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvatarViewResponse) ProtoMessage() {}

func (x *GetAvatarViewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_avatar_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvatarViewResponse.ProtoReflect.Descriptor instead.
func (*GetAvatarViewResponse) Descriptor() ([]byte, []int) {
	return file_grpc_proto_avatar_proto_rawDescGZIP(), []int{6}
}

func (x *GetAvatarViewResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type TESTUploadImageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Data:
	//
	//	*TESTUploadImageRequest_Info
	//	*TESTUploadImageRequest_ChunkData
	Data isTESTUploadImageRequest_Data `protobuf_oneof:"data"`
}

func (x *TESTUploadImageRequest) Reset() {
	*x = TESTUploadImageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_avatar_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TESTUploadImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TESTUploadImageRequest) ProtoMessage() {}

func (x *TESTUploadImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_avatar_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TESTUploadImageRequest.ProtoReflect.Descriptor instead.
func (*TESTUploadImageRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_avatar_proto_rawDescGZIP(), []int{7}
}

func (m *TESTUploadImageRequest) GetData() isTESTUploadImageRequest_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *TESTUploadImageRequest) GetInfo() *TESTImageInfo {
	if x, ok := x.GetData().(*TESTUploadImageRequest_Info); ok {
		return x.Info
	}
	return nil
}

func (x *TESTUploadImageRequest) GetChunkData() []byte {
	if x, ok := x.GetData().(*TESTUploadImageRequest_ChunkData); ok {
		return x.ChunkData
	}
	return nil
}

type isTESTUploadImageRequest_Data interface {
	isTESTUploadImageRequest_Data()
}

type TESTUploadImageRequest_Info struct {
	Info *TESTImageInfo `protobuf:"bytes,1,opt,name=info,proto3,oneof"`
}

type TESTUploadImageRequest_ChunkData struct {
	ChunkData []byte `protobuf:"bytes,2,opt,name=chunk_data,json=chunkData,proto3,oneof"`
}

func (*TESTUploadImageRequest_Info) isTESTUploadImageRequest_Data() {}

func (*TESTUploadImageRequest_ChunkData) isTESTUploadImageRequest_Data() {}

type TESTImageInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type     string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Filename string `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
}

func (x *TESTImageInfo) Reset() {
	*x = TESTImageInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_avatar_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TESTImageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TESTImageInfo) ProtoMessage() {}

func (x *TESTImageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_avatar_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TESTImageInfo.ProtoReflect.Descriptor instead.
func (*TESTImageInfo) Descriptor() ([]byte, []int) {
	return file_grpc_proto_avatar_proto_rawDescGZIP(), []int{8}
}

func (x *TESTImageInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TESTImageInfo) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type TESTUploadImageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GeneratedPath string `protobuf:"bytes,1,opt,name=generatedPath,proto3" json:"generatedPath,omitempty"`
}

func (x *TESTUploadImageResponse) Reset() {
	*x = TESTUploadImageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_avatar_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TESTUploadImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TESTUploadImageResponse) ProtoMessage() {}

func (x *TESTUploadImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_avatar_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TESTUploadImageResponse.ProtoReflect.Descriptor instead.
func (*TESTUploadImageResponse) Descriptor() ([]byte, []int) {
	return file_grpc_proto_avatar_proto_rawDescGZIP(), []int{9}
}

func (x *TESTUploadImageResponse) GetGeneratedPath() string {
	if x != nil {
		return x.GeneratedPath
	}
	return ""
}

var File_grpc_proto_avatar_proto protoreflect.FileDescriptor

var file_grpc_proto_avatar_proto_rawDesc = []byte{
	0x0a, 0x17, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x76, 0x61,
	0x74, 0x61, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x74, 0x65, 0x6d, 0x70, 0x6c,
	0x61, 0x74, 0x65, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x66, 0x0a, 0x06, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x12, 0x24, 0x0a, 0x0d, 0x67, 0x65,
	0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x50, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0d, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x50, 0x61, 0x74, 0x68,
	0x12, 0x22, 0x0a, 0x0c, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x31, 0x0a, 0x13, 0x55, 0x70, 0x6c, 0x6f,
	0x61, 0x64, 0x47, 0x65, 0x74, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x50, 0x0a, 0x14, 0x55,
	0x70, 0x6c, 0x6f, 0x61, 0x64, 0x47, 0x65, 0x74, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x26, 0x0a, 0x0e, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x54, 0x6f,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x54, 0x6f, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x22, 0x2c, 0x0a,
	0x14, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x29, 0x0a, 0x15, 0x55,
	0x70, 0x6c, 0x6f, 0x61, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x2e, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x41, 0x76, 0x61,
	0x74, 0x61, 0x72, 0x56, 0x69, 0x65, 0x77, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x29, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x41, 0x76, 0x61,
	0x74, 0x61, 0x72, 0x56, 0x69, 0x65, 0x77, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72,
	0x6c, 0x22, 0x70, 0x0a, 0x16, 0x54, 0x45, 0x53, 0x54, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49,
	0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x04, 0x69,
	0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x74, 0x65, 0x6d, 0x70,
	0x6c, 0x61, 0x74, 0x65, 0x2e, 0x54, 0x45, 0x53, 0x54, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x48, 0x00, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x1f, 0x0a, 0x0a, 0x63, 0x68,
	0x75, 0x6e, 0x6b, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00,
	0x52, 0x09, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x44, 0x61, 0x74, 0x61, 0x42, 0x06, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x22, 0x3f, 0x0a, 0x0d, 0x54, 0x45, 0x53, 0x54, 0x49, 0x6d, 0x61, 0x67, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65,
	0x6e, 0x61, 0x6d, 0x65, 0x22, 0x3f, 0x0a, 0x17, 0x54, 0x45, 0x53, 0x54, 0x55, 0x70, 0x6c, 0x6f,
	0x61, 0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x24, 0x0a, 0x0d, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x50, 0x61, 0x74, 0x68,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65,
	0x64, 0x50, 0x61, 0x74, 0x68, 0x32, 0x96, 0x03, 0x0a, 0x0d, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4d, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x55, 0x70,
	0x6c, 0x6f, 0x61, 0x64, 0x55, 0x52, 0x4c, 0x12, 0x1d, 0x2e, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61,
	0x74, 0x65, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x47, 0x65, 0x74, 0x55, 0x72, 0x6c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74,
	0x65, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x47, 0x65, 0x74, 0x55, 0x72, 0x6c, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x50, 0x0a, 0x0d, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72,
	0x6d, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x1e, 0x2e, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61,
	0x74, 0x65, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61,
	0x74, 0x65, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x58, 0x0a, 0x0f, 0x54, 0x45, 0x53, 0x54,
	0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x20, 0x2e, 0x74, 0x65,
	0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x2e, 0x54, 0x45, 0x53, 0x54, 0x55, 0x70, 0x6c, 0x6f, 0x61,
	0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e,
	0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x2e, 0x54, 0x45, 0x53, 0x54, 0x55, 0x70, 0x6c,
	0x6f, 0x61, 0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x28, 0x01, 0x12, 0x38, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x16, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x50, 0x0a, 0x0d,
	0x47, 0x65, 0x74, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x56, 0x69, 0x65, 0x77, 0x12, 0x1e, 0x2e,
	0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x76, 0x61, 0x74,
	0x61, 0x72, 0x56, 0x69, 0x65, 0x77, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e,
	0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x76, 0x61, 0x74,
	0x61, 0x72, 0x56, 0x69, 0x65, 0x77, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0d,
	0x5a, 0x0b, 0x70, 0x62, 0x2f, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_proto_avatar_proto_rawDescOnce sync.Once
	file_grpc_proto_avatar_proto_rawDescData = file_grpc_proto_avatar_proto_rawDesc
)

func file_grpc_proto_avatar_proto_rawDescGZIP() []byte {
	file_grpc_proto_avatar_proto_rawDescOnce.Do(func() {
		file_grpc_proto_avatar_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_proto_avatar_proto_rawDescData)
	})
	return file_grpc_proto_avatar_proto_rawDescData
}

var file_grpc_proto_avatar_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_grpc_proto_avatar_proto_goTypes = []interface{}{
	(*Avatar)(nil),                  // 0: template.Avatar
	(*UploadGetUrlRequest)(nil),     // 1: template.UploadGetUrlRequest
	(*UploadGetUrlResponse)(nil),    // 2: template.UploadGetUrlResponse
	(*UploadConfirmRequest)(nil),    // 3: template.UploadConfirmRequest
	(*UploadConfirmResponse)(nil),   // 4: template.UploadConfirmResponse
	(*GetAvatarViewRequest)(nil),    // 5: template.GetAvatarViewRequest
	(*GetAvatarViewResponse)(nil),   // 6: template.GetAvatarViewResponse
	(*TESTUploadImageRequest)(nil),  // 7: template.TESTUploadImageRequest
	(*TESTImageInfo)(nil),           // 8: template.TESTImageInfo
	(*TESTUploadImageResponse)(nil), // 9: template.TESTUploadImageResponse
	(*emptypb.Empty)(nil),           // 10: google.protobuf.Empty
}
var file_grpc_proto_avatar_proto_depIdxs = []int32{
	8,  // 0: template.TESTUploadImageRequest.info:type_name -> template.TESTImageInfo
	1,  // 1: template.AvatarService.GetUploadURL:input_type -> template.UploadGetUrlRequest
	3,  // 2: template.AvatarService.ConfirmUpload:input_type -> template.UploadConfirmRequest
	7,  // 3: template.AvatarService.TESTUploadImage:input_type -> template.TESTUploadImageRequest
	10, // 4: template.AvatarService.Delete:input_type -> google.protobuf.Empty
	5,  // 5: template.AvatarService.GetAvatarView:input_type -> template.GetAvatarViewRequest
	2,  // 6: template.AvatarService.GetUploadURL:output_type -> template.UploadGetUrlResponse
	4,  // 7: template.AvatarService.ConfirmUpload:output_type -> template.UploadConfirmResponse
	9,  // 8: template.AvatarService.TESTUploadImage:output_type -> template.TESTUploadImageResponse
	10, // 9: template.AvatarService.Delete:output_type -> google.protobuf.Empty
	6,  // 10: template.AvatarService.GetAvatarView:output_type -> template.GetAvatarViewResponse
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_grpc_proto_avatar_proto_init() }
func file_grpc_proto_avatar_proto_init() {
	if File_grpc_proto_avatar_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_proto_avatar_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Avatar); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_proto_avatar_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadGetUrlRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_proto_avatar_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadGetUrlResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_proto_avatar_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadConfirmRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_proto_avatar_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadConfirmResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_proto_avatar_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAvatarViewRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_proto_avatar_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAvatarViewResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_proto_avatar_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TESTUploadImageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_proto_avatar_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TESTImageInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_proto_avatar_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TESTUploadImageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_grpc_proto_avatar_proto_msgTypes[7].OneofWrappers = []interface{}{
		(*TESTUploadImageRequest_Info)(nil),
		(*TESTUploadImageRequest_ChunkData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_proto_avatar_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_proto_avatar_proto_goTypes,
		DependencyIndexes: file_grpc_proto_avatar_proto_depIdxs,
		MessageInfos:      file_grpc_proto_avatar_proto_msgTypes,
	}.Build()
	File_grpc_proto_avatar_proto = out.File
	file_grpc_proto_avatar_proto_rawDesc = nil
	file_grpc_proto_avatar_proto_goTypes = nil
	file_grpc_proto_avatar_proto_depIdxs = nil
}
