name: GO GRPC Server CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.15

      # - name: Build
      #   run: go build -v ./...
      #   working-directory: grpc-server-go

      - name: Test
        run: go test -v ./helpers/...
        working-directory: grpc-server-go
